### PR TITLE
Add ability to pass the Consul ACL Token when interacting with Consul…

### PR DESCRIPTION
**Pull request by jwmajors81**
…'s session api.

This is a PR in response to https://github.com/Ecwid/consul-api/issues/102

### CODE REVIEW

**Comment by gil-zhao** [comment]
Hi, is there any plan to merge this PR?

**Comment by young-usnavi** [comment]
@vgv  - looks like using sessions + ACL tokens is a desired feature (see https://github.com/Ecwid/consul-api/issues/102 and https://github.com/Ecwid/consul-api/issues/154)  

Any chance this PR can be reviewed?

**Comment by young-usnavi** [comment]
This would be very helpful.  Can this be reviewed?  Is this project still active?

**Comment by vgv** [comment]
> This would be very helpful. Can this be reviewed? Is this project still active?

Yes, this project is active. Give me a couple of days, please

**Comment by nickcodefresh** [comment]
I too am waiting on this merge. Thanks

**Comment by vgv** [comment]
Thank you!

**Comment by vgv** [comment]
Version 1.4.1 with these changes has been released

**Pull request merged**
