### PR TITLE
Support ACL tokens for health and catalog service endpoints

### PR DESCRIPTION
**Pull request by sirlatrom**
Replaces and closes #57.

Signed-off-by: Sune Keller <absukl@almbrand.dk>

### CODE REVIEW

**Comment by spencergibb** [comment]
Thanks guys, this will unblock https://github.com/spring-cloud/spring-cloud-consul/issues/201

**Comment by sirlatrom** [comment]
Pinging @vgv just to hear if there's anyone else who might take a look

**Comment by vgv** [comment]
Thank you.

**Comment by vgv** [comment]
> Pinging @vgv just to hear if there's anyone else who might take a look

@sirlatrom Sorry for long response!

**Pull request merged**
