### PR TITLE
Support for setting keys in different data centers, and for declaring sessions with 'delete' behavior.

### PR DESCRIPTION
**Pull request by jcasillas-boxfish**
Apologies for the auto-format that kicked in on the affected files.  This is a very simple update enabling key features that we need.

Thank you!

### CODE REVIEW

**Comment by vgv** [comment]
I do not have enough time right now, sorry.
I will look into your pull request in next 3-5 days.

**Comment by jcasillas-boxfish** [comment]
Thank you for your reply.  I understand you have time constraints -- I am
building off of our fork and will transition back to yours once you are
able to update.  Sorry for the formatting -- will watch for that next time.

Best,
Jose

**Comment by vgv** [comment]
Hi

I will not accept your merge commit, but I took your patch, slightly rework and commit.
Thank you for code!

**Comment by jcasillas-boxfish** [comment]
Thank you sir, appreciate your integration.

Best,
Jose

**Pull request closed without merging**
