### PR TITLE
pass external http client to raw consul client

### PR DESCRIPTION
**Pull request by matlockx**

### CODE REVIEW

**Comment by vgv** [comment]
Thank you

**Comment by matlockx** [comment]
Wow, that was fast. Can we get a new release?

**Comment by vgv** [comment]
I'm going out to launch, so give me one hour :)

**Comment by matlockx** [comment]
:) sure.  Thanks a lot

**Comment by vgv** [comment]
done
New version has uploaded into our nexus repo, version 1.1.1

**Comment by matlockx** [comment]
Great. Thanks a lot. It's already integrated into our code base and working fine :)
Just in case you are interested why we need it: when configured for a consul IP of a virtual box for testing with a host only network adapter and when the virtual box is not running the default connection timeout is quite high and blocking.

**Pull request merged**
